### ISSUE TITLE
我使用官网的配置，将链接转成卡片之后，卡片无法再选中编辑

### ISSUE THREAD

**Issue by tankpanv** [wangeditor-team/wangEditor-plugin-link-card#1]
我使用官网的配置，将链接转成卡片之后，卡片无法再选中编辑。不指定这个是不是bug

**Comment by wangfupeng1988** [comment]
目前链接卡片不支持编辑功能。如非常需要，可自行扩展开发 https://www.wangeditor.com/v5/guide/development.html#modalmenu

**Comment by 0131LWG** [comment]
> 

 目前这个链接打不开哦，我需要自定义一些模块，构建一些复杂了html样式，能否插入到富文本中并可编辑呢？

**Comment by wangfupeng1988** [comment]
@0131LWG 原则上是可以的，不过复杂的模块，写起来也很麻烦

**Comment by 0131LWG** [comment]
> @0131LWG 原则上是可以的，不过复杂的模块，写起来也很麻烦

![image](https://user-images.githubusercontent.com/30310735/164640325-6708cbf9-affc-40e5-a461-48a303d75ee1.png)
![image](https://user-images.githubusercontent.com/30310735/164642761-09e9011c-fa40-4413-8264-52127978de77.png)

我想做的大致是上图的效果，然后可编辑文字，还会有一些换颜色的操作（目前想到的操作是使用监听dom的方式完成），还在调研中，但编辑文字的功能还没有看到有实现的案例，不知能否实现呢？

**Comment by wangfupeng1988** [comment]
这个就比较麻烦了。你这不是富文本编辑器，而更像一个网页编辑器，一个低代码或零代码平台。

**Comment by 0131LWG** [comment]
> 这个就比较麻烦了。你这不是富文本编辑器，而更像一个网页编辑器，一个低代码或零代码平台。

![image](https://user-images.githubusercontent.com/30310735/164688132-cfbf4a7b-7453-4642-97d4-e7464405143b.png)

是的，想做一个零代码的平台，目前能生成这样，但一旦删除就会整个删除，并不能进行编辑，请问是否有什么方式可实现正常的删除编辑呢？

**Comment by 0131LWG** [comment]
> > 这个就比较麻烦了。你这不是富文本编辑器，而更像一个网页编辑器，一个低代码或零代码平台。
> 
> ![image](https://user-images.githubusercontent.com/30310735/164688132-cfbf4a7b-7453-4642-97d4-e7464405143b.png)
> 
> 是的，想做一个零代码的平台，目前能生成这样，但一旦删除就会整个删除，并不能进行编辑，请问是否有什么方式可实现正常的删除编辑呢？

设置contenteditable: true无效果

**Comment by xuedongwang** [comment]
大佬，这个转成卡片之后，点击卡片不能跳转，请问这个设计就是如此还是？

**Comment by wangfupeng1988** [comment]
@xuedongwang 你是想在编辑器里跳转？还是显示 HTML 时跳转？

**Comment by xuedongwang** [comment]
> 

两个地方我都想能跳转。我预览时用的是编辑器的readonly模式。

**Comment by xuedongwang** [comment]
@wangfupeng1988 两个地方我都想能跳转。我预览时用的是编辑器的readonly模式。

**Comment by wangfupeng1988** [comment]
@xuedongwang  编辑器 readOnly 时可以跳转

但正常编辑器时不能跳转，否则太影响使用体验了。
